### ISSUE TITLE
Use os.listdir instead of os.walk

### ISSUE THREAD

**Issue by crearo** [prat96/Thermal_calib_Generator#4]
- [x] `os.walk` is useful when you want to traverse recursively. `os.listdir` is better for the use-case in `gain`. 
- [x] You needn't maintain a separate variable for index/loopcount. Can use `enumerate()`. For example, `>>> for index, f in enumerate(os.listdir('./')):`

**Comment by prat96** [comment]
Done.
commit - d57c4a1db30c54db7ca2655e2f40834b6f84eccc
